import type { Metadata } from "next";
import { Geist_Mono, Inter } from "next/font/google";
import { notFound } from "next/navigation";
import { Footer } from "@/components/footer";
import { Navbar } from "@/components/navbar";
import { dictionaryFor } from "@/lib/i18n/dictionaries";
import { LOCALES, hasLocale } from "@/lib/i18n/locales";
import "../globals.css";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/** Pre-renders every page for all four locales. */
export async function generateStaticParams() {
  return LOCALES.map(({ value }) => ({ lang: value }));
}

/** Any locale outside the list above is a 404 rather than a runtime error. */
export const dynamicParams = false;

export default async function RootLayout({
  children,
  params,
}: LayoutProps<"/[lang]">) {
  const { lang } = await params;

  if (!hasLocale(lang)) {
    notFound();
  }

  const dict = dictionaryFor(lang);

  return (
    <html
      lang={lang}
      className={`${inter.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Navbar locale={lang} dict={dict} />
        {children}
        <Footer locale={lang} dict={dict} />
      </body>
    </html>
  );
}
